backend:
  name: git-gateway
  branch: master
  accept_roles: owner

local_backend: true

media_folder: static/img
public_folder: /img
publish_mode: editorial_workflow # Enable drafts

collections:
  - label: "Businesses (English)"
    extension: en.md
    format: frontmatter
    name: "english_posts"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    filter: { field: "lang", value: "en" }
    fields:
      - { label: "Id", name: id, widget: number }
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Business Name", name: "title", widget: "string" }
      - { label: "Primary Image", name: "primary_image", widget: "file" }
      - { label: "Publish Date", name: "date", widget: "datetime" }

      #
      - { label: "Description", name: "description", widget: "text" }
      - {
          label: "Language",
          name: "lang",
          widget: "select",
          options: ["en", "cn", "it"],
        }
      - { label: "Path", name: "path", widget: "string" }
      - {
          label: "Intro Paragraph",
          name: "intro_paragraph",
          widget: "text",
          required: false,
        }

      # Full business description
      - {
          label: "About the business",
          name: "about_the_business",
          widget: "text",
        }

      # Restaurant, Bookstore, etc
      - {
          label: "Business Type",
          name: "business_type",
          widget: "list",
          default: ["restaurant"],
        }

      # ignore for now
      - { label: "Tags", name: "tags", widget: "hidden", required: false }

      # Delivery, Takeout, Donations
      - { label: "Services Offered", name: "services_offered", widget: "list" }

      - { label: "Address", name: "address", widget: "string" }
      - {
          label: "Homepage Link",
          name: "homepage-link",
          widget: "string",
          required: false,
        }
      - {
          label: "Social Link",
          name: "social-link",
          widget: "string",
          required: false,
        }

  - label: "Blog in Italiano"
    extension: it.md
    format: frontmatter
    name: "Italiano_posts"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    filter: { field: "lang", value: "it" }
    fields:
      - { label: "Id", name: id, widget: number }
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Titolo", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Descrizione", name: "description", widget: "text" }
      - {
          label: "Linguaggio",
          name: "lang",
          widget: "select",
          options: ["en", "it"],
        }
      - { label: "Percorso", name: "path", widget: "string" }
      - {
          label: "Paragrafo introduttivo",
          name: "intro_paragraph",
          widget: "markdown",
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }

  - label: "Articles tree"
    extension: json
    format: json
    name: "articles"
    folder: "src/data/articles"
    create: false
    delete: false
    fields:
      - {
          label: "Titolo / Title",
          name: "title",
          widget: "string",
          default: "home",
        }
      - label: "List of articles"
        name: "articles"
        widget: "list"
        hint: >-
          This is a json file where to set the links for every article in the switcher selector
          for the language, fill the id and the name of the article for both languages
        fields:
          - { label: "id", name: id, widget: number }
          - { label: "en", name: en, widget: "string" }
          - { label: "it", name: it, widget: "string" }
