backend:
  name: git-gateway
  branch: master
  accept_roles: owner

local_backend: true

media_folder: static/img
public_folder: /img
publish_mode: editorial_workflow # Enable drafts

collections:
  - label: "Businesses (English)"
    extension: en.md
    format: frontmatter
    name: "english_posts"
    folder: "src/pages/blog"
    create: true
    slug: "{{title}}"
    filter: { field: "lang", value: "en" }
    fields:
      - label: "id"
        name: "id"
        widget: "hidden"
        default: "01"

      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Business Name", name: "title", widget: "string" }
      - { label: "Primary Image", name: "primary_image", widget: "image" }
      - { label: "Publish Date", name: "date", widget: "datetime" }

      #
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Language", name: "lang", widget: "hidden", default: "en" }

      # Business Story
      - { label: "Story", name: "story", widget: "text" }

      # Restaurant, Bookstore, etc
      - {
          label: "Business Type",
          name: "business_type",
          widget: "list",
          default: ["restaurant"],
        }

      # ignore for now
      - { label: "Tags", name: "tags", widget: "hidden", required: false }

      # Delivery, Takeout, Donations
      - {
          label: "Services Offered",
          name: "services_offered",
          widget: "list",
          default: ["delivery", "takout", "donations"],
        }

      - { label: "Address", name: "address", widget: "text" }
      - { label: "Phone", name: "phone", widget: "string" }

      - label: "Homepage"
        name: "homepage_link"
        widget: "string"
        required: false
      - label: "Instagram"
        name: "instagram_link"
        widget: "string"
        required: false
      - label: "Facebook"
        name: "facebook_link"
        widget: "string"
        required: false
      - label: "Twitter"
        name: "twitter_link"
        widget: "string"
        required: false
      - label: "More images"
        name: "more_images"
        widget: "image"
        required: false
        media_library:
          config:
            multiple: true

  - label: "Businesses (Chinese)"
    extension: cn.md
    format: frontmatter
    name: "chinese_businesses"
    folder: "src/pages/businesses"
    create: true
    slug: "{{title}}"
    filter: { field: "lang", value: "cn" }
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Business Name", name: "title", widget: "string" }
      - { label: "Primary Image", name: "primary_image", widget: "image" }
      - { label: "Publish Date", name: "date", widget: "datetime" }

      #
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Language", name: "lang", widget: "hidden", default: "en" }

      # Business Story
      - { label: "Story", name: "story", widget: "text" }

      # Restaurant, Bookstore, etc
      - {
          label: "Business Type",
          name: "business_type",
          widget: "list",
          default: ["restaurant"],
        }

      # ignore for now
      - { label: "Tags", name: "tags", widget: "hidden", required: false }

      # Delivery, Takeout, Donations
      - {
          label: "Services Offered",
          name: "services_offered",
          widget: "list",
          default: ["delivery", "takout", "donations"],
        }

      - { label: "Address", name: "address", widget: "text" }
      - { label: "Phone", name: "phone", widget: "string" }

      - label: "Homepage"
        name: "homepage_link"
        widget: "string"
        required: false
      - label: "Instagram"
        name: "instagram_link"
        widget: "string"
        required: false
      - label: "Facebook"
        name: "facebook_link"
        widget: "string"
        required: false
      - label: "Twitter"
        name: "twitter_link"
        widget: "string"
        required: false
      - label: "More images"
        name: "more_images"
        widget: "image"
        required: false
        media_library:
          config:
            multiple: true

  - label: "Articles tree"
    extension: json
    format: json
    name: "articles"
    folder: "src/data/articles"
    create: false
    delete: false
    fields:
      - {
          label: "Titolo / Title",
          name: "title",
          widget: "string",
          default: "home",
        }
      - label: "List of articles"
        name: "articles"
        widget: "list"
        hint: >-
          This is a json file where to set the links for every article in the switcher selector
          for the language, fill the id and the name of the article for both languages
        fields:
          - { label: "id", name: id, widget: number }
          - { label: "en", name: en, widget: "string" }
          - { label: "it", name: it, widget: "string" }
